### ISSUE TITLE
Proposal for Official Support

### ISSUE THREAD

**Issue by kuitos** [mobxjs/mobx-vue#1]
Hi @mweststrate
Recently I built this library to combine mobx with vue through a simple api what like mobx-react does, now it released v1.0.0 and reached 100% code coverage already, could you please donate some time to make a review and check is it good enough to move to mobxjs organization?

**Comment by mweststrate** [comment]
Looks good! Should be compatible out of the box immediately as well with MobX 5, which means that it will support direct manipulation of objects, arrays etc, which is all more cumbersome in Vue ;-)

Feel free to submit an organization move request. I'll add you as collaborator as well.

**Comment by mweststrate** [comment]
How does this library relate to https://github.com/dwqs/vue-mobx? Should the efforts be combined?

**Comment by mweststrate** [comment]
N.B. note that moving it to the organisation means that there is a commitment @kuitos to support it from your side? I don't think there are a lot of other experienced Vue users in collaborators team of MobXJS :).

**Comment by kuitos** [comment]
@mweststrate vue-mobx was not maintained any more, see https://github.com/dwqs/vue-mobx/issues/4 . The author recommended [movue](https://github.com/nighca/movue) .
And, the author of movue had raised a question which just mobx-vue solved: https://github.com/nighca/movue/issues/16 . 

Both the libraries are inspired by [vue-rx](https://github.com/vuejs/vue-rx), which I think would weaken the mobx power(sorry to @nighca 😜), I will post a article to explain this these days.

> note that moving it to the organisation means that there is a commitment @kuitos to support it from your side?

That challenge is what I want!

>  I don't think there are a lot of other experienced Vue users in collaborators team of MobXJS

Yes that is what I concerned, fortunately I had use mobx-vue in our production to earn experience.

**Comment by nighca** [comment]
Great effort @kuitos! Let me know if I can offer help.

**Comment by kuitos** [comment]
Firstly, recommend mobx-vue on movue haha.@nighca :stuck_out_tongue_winking_eye:

**Comment by nighca** [comment]
@kuitos Sure. I [introduced mobx-vue in README](https://github.com/nighca/movue/commit/c28d28df8010e49c184cc78a62c8b13890e274c7). :)
By the way, I've got some ideas about mobx-vue and will explain in another issue.

**Comment by kuitos** [comment]
all right:ok_hand:
