### ISSUE TITLE
Doesn't appear to work with mobx-state-tree. Should it?

### ISSUE THREAD

**Issue by pillowsoft** [mobxjs/mobx-vue#12]
I create two stores, one a mobx store and one a mobx-state-tree store.  I then hooked them both up to a vue view, per the readme. The mobx store works (i.e component updates when the store changes), but the view does not update on changes in the mobx-state-tree store.

**Comment by kuitos** [comment]
Checked and it works well with my demo, could u give a [codesandbox](https://codesandbox.io/) link to reproduce it?

**Comment by pillowsoft** [comment]
I could not get [codesandbox](https://codesandbox.io/) to work (it had issues with multiple copies of mobx). Here's a repo that demos the issue: [demo repo](https://github.com/pillowsoft/mobx-state-tree-vue-bug-demo)

**Comment by kuitos** [comment]
I had run a codesandbox demo to revalidate it and found nothing wrong. Could you check any thing I had missed? https://codesandbox.io/s/rjqr3pl34o

**Comment by pillowsoft** [comment]
Thanks! Yours works, but if you use a nested mst store, it breaks (at least
for me).

Try this one with a nested mst store: https://codesandbox.io/s/x9qmzpkj84

I.e. the code is modifying the mst correctly, but re-renders are not
happening on nested chnages.

**Comment by kuitos** [comment]
With your codesandbox demo it worked well in my side, mst changes triggered. Anything I missed?

![kapture 2018-06-24 at 17 47 07](https://user-images.githubusercontent.com/5206843/41817918-f3b171ce-77d6-11e8-8a0e-6134fbcfd9d4.gif)

**Comment by pillowsoft** [comment]
Egads, you're right. No sure what the heck I was doing, but it does indeed
seem to be working now. So sorry for the confusion. Thank you and I owe you
a drink!

**Comment by kuitos** [comment]
Never mind! Feel free to ask any questions!😀
