### ISSUE TITLE
Most of the tests are failing

### ISSUE THREAD

**Issue by snaptopixel** [mobxjs/mobx-vue#18]
I was gearing up to start a PR but noticed the bulk of the tests are failing? Is there something wrong with the lib, or are the tests outdated?

![](https://cl.ly/3l072H1y2a2N/Image%202018-07-18%20at%203.06.20%20PM.png)

**Comment by kuitos** [comment]
had checked the local and latest [travis building](https://travis-ci.org/mobxjs/mobx-vue), nothing broken yet. Could you have a try to look into the error stack or rebuild the dependencies(delete node_modeuls and rerun `npm i`) with npm@5 again?

**Comment by snaptopixel** [comment]
Ok, I had used `yarn` previously, but following your directions it's working now. Thanks, closing!

**Comment by kuitos** [comment]
expecting for your pr 😀

**Comment by snaptopixel** [comment]
Still working on my PR @kuitos, I wanted to re-open this because the tests fail whenever I update `vue-test-utils`. The only way to get them working again is to revert the change in package.json and package-lock.json, then `npm i` and they will run again...

**Comment by kuitos** [comment]
`vue-test-utils` is beta still, we should keep it locked at current period imo.

**Comment by kuitos** [comment]
Had submitted a pr to fix this issue: https://github.com/vuejs/vue-test-utils/pull/856

**Comment by kuitos** [comment]
fixed

**Comment by snaptopixel** [comment]
Great work @kuitos! Thanks for looking into it and fixing vue-test-utils ;)
