### ISSUE TITLE
any guide about isomorphic mobx with vue???

### ISSUE THREAD

**Issue by cocodrino** [mobxjs/mobx-vue#20]
Hi guys, I'd like to use mobx and vue isomorphic, which is the best way to achieve this??? would be great if mubx would be incorporated to nuxt as alternative to redux...any plan for this???

thank you guys for the great job...

**Comment by kuitos** [comment]
uh... Exactly I do not understand what u want😅
If you wanna support [SSR](https://ssr.vuejs.org/) with mobx, u could check this lib: https://github.com/mmlpxjs/mmlpx#time-travelling
