### ISSUE TITLE
What about Provider decorator?

### ISSUE THREAD

**Issue by pgalwa** [mobxjs/mobx-vue#21]
Hey,
Is any common pattern for mobx-vue which is similar to using Provider decorator from a mobx-react?

Also I have a question about using it with routing. Can I inject specified substore/ substores to exact route?

**Comment by kuitos** [comment]
@pgalwa 
As the context concept did not occur in vue system, so the `Provider` approach does not have a really usage in vue app imo.
But if you are really want the `Provider` mechanism, you could try the native [provide/inject](https://vuejs.org/v2/api/#provide-inject) which provided by vue.

> Also I have a question about using it with routing. Can I inject specified substore/ substores to exact route?

Could you please show some code to describe this use case?

**Comment by pgalwa** [comment]
> Could you please show some code to describe this use case?


I meant something like in https://github.com/alisd23/mobx-react-router but I see you answered my question :) 

So thanks 👍

**Comment by kuitos** [comment]
Cool😀
Thanks for your feedback!
