### ISSUE TITLE
Use mobx-vue cause hot reload mount component twice

### ISSUE THREAD

**Issue by linyupark** [mobxjs/mobx-vue#25]

**Comment by kuitos** [comment]
could you provide a minimal reproduction or a codesandbox example?

**Comment by linyupark** [comment]
https://codesandbox.io/s/4lx1nr9vp7
App.vue

> console.log('change content')

watch the change of console print content, mounted method will call twice, the first time is the code before change and then call the changed code.

**Comment by kuitos** [comment]
@linyupark I will handle the issue this weekend, thanks!

**Comment by kuitos** [comment]
@linyupark fixed and released v2.0.8, sorry for the delay~
