### ISSUE TITLE
`observer.js` missing from current dist/package

### ISSUE THREAD

**Issue by doriandrn** [mobxjs/mobx-vue#48]
Hello,

I've installed the package from npm and i was getting this error:

`Module not found: Error: Can't resolve './observer' in '/Users/........./node_modules/mobx-vue/esm'`

The file seems to be missing indeed from the package after checking node_modules. 
<img width="180" alt="Captură de ecran din 2020-08-05 la 09 24 15" src="https://user-images.githubusercontent.com/13486356/89378989-a2864580-d6fd-11ea-9e66-a1294879f787.png">

This is just a heads-up! I had to (re)build the project and move the files manually to get it working. Other than that, nice job!

**Comment by kuitos** [comment]
Checked the npm package, it seems not missing https://unpkg.com/browse/mobx-vue@2.0.10/esm/observer.js

could you pls check your version of installed mobx-vue package?

**Comment by doriandrn** [comment]
Thanks for the suggestion, it seemed to be a problem with yarn installing it. After switching to npm, everything worked fine.
