### ISSUE TITLE
Vue 3 Compatibility

### ISSUE THREAD

**Issue by doc987** [mobxjs/mobx-vue#50]
mobx-vue doesn't seem to work with Vue 3 ([https://v3.vuejs.org/](https://v3.vuejs.org/)).  Is there going to be an update for that?

**Comment by ProTip** [comment]
Vue 3 has just been released. I'm somewhat familiar with the existing binding code, but Vue 3 has been re-written and I have yet to really find the lifecycle and re-render code haha. Once I can make sense of it I may be able to write new bindings..

**Comment by AllenMRbai** [comment]
hope mobx-vue support vue 3 too.
our team want to refactor old project into vue 3. vuex is complex , so we want to use mobx instead.
however, there haven't lib support vue 3 yet.

**Comment by doxiaodong** [comment]
Hello, I support vue3 with observer in https://github.com/umijs/neeko/blob/master/src/vue/observer.ts. Hope it useful.

**Comment by anri-asaturov** [comment]
I just tested mobx-vue with `vue@3.0.11`class component and `mobx@6.1.8` and it works. What am I doing wrong?

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/mobx-vue-lite

**Comment by iChenLei** [comment]
https://github.com/mobxjs/mobx-vue-lite , look here
