### ISSUE TITLE
TypeError: reaction.getDisposer is not a function

### ISSUE THREAD

**Issue by MisicDemone** [mobxjs/mobx-vue#57]
codesandbox: [https://codesandbox.io/s/gallant-butterfly-3clxm](https://codesandbox.io/s/gallant-butterfly-3clxm)

Maybe it should be `reaction.getDisposer_`?

**Comment by standbyoneself** [comment]
No, it shouldn't. Change MobX version to 5.x.

**Comment by abreumatheus** [comment]
I'm facing the exact same issue, and i don't think "Go back to 5.x" is a great answer.
Everything is working fine here, but i'm getting this warning on the console.

**Comment by asd116725** [comment]
> Change MobX version to 5.x.

It can be worked. Change MobX version to 5.x.

**Comment by EthianWong** [comment]
@doxiaodong @kuitos @azzra 
Can MobX v6 be supported?

**Comment by iChenLei** [comment]
Will release a v2.1.0 to support mobx v6 later @EthianWong @MisicDemone

**Comment by iChenLei** [comment]
v2.1.0 released, support mobx v6, but this is a breaking change, **v2.1.0 not support mobx v2/v3/v4/v5**!
