### ISSUE TITLE
Unable to resolve signature of class decorator when called as an expression.

### ISSUE THREAD

**Issue by doxiaodong** [mobxjs/mobx-vue#6]
![image](https://user-images.githubusercontent.com/6927481/41149090-363d86a0-6b3d-11e8-9f7b-747bd340e458.png)
![image](https://user-images.githubusercontent.com/6927481/41149102-4386a152-6b3d-11e8-9088-984284ed7ae1.png)

**Comment by kuitos** [comment]
fixed and released v2.0.3!
