### ISSUE TITLE
Mobx6 not working

### ISSUE THREAD

**Issue by snapxtp** [mobxjs/mobx-vue#73]
When I download mobx-vue, it comes with version 2.0.11 and doesn't work with mobx6, it gives a webpack object error in the console.
Does this plugin work for vue.js with mobx 6 without using @pattern?

Thanks.

**Comment by iChenLei** [comment]
Mobx6 support added by https://github.com/mobxjs/mobx-vue/pull/69, not release now. I will release a alpha version as soon as possible.

**Comment by iChenLei** [comment]
And vue3 support is still work in progress.

**Comment by iChenLei** [comment]
@snapxtp Please try `npm install mobx-vue@next `, we release a alpha version which support mobx6 and vue2.x, your feedback is very important for us, Thanks.

**Comment by snapxtp** [comment]
Great I will try it and share the feedback with you. Thanks for the great job

**Comment by snapxtp** [comment]
It didn't work in my project, I couldn't compile

"mobx": "^6.3.2",
"mobx-vue": "^2.1.0-alpha.4",
"vue": "^2.6.11",

note: The error I get when upgrading to mobx-vue alpha version. I completely upgraded the node_module folder and updated the versions.

ERROR:

* mobx-vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Home.vue?vue&type=script&lang=js& and 2 others

To install it, you can run: npm install --save mobx-vue

**Comment by iChenLei** [comment]
Thanks for feedback, I will debug it today. ❤️

**Comment by iChenLei** [comment]
@snapxtp Can you try it now `2.1.0-alpha.5`? I fix the Github Actions bug, build the correct artifacts to npm registry. Thanks u for fast try and give me feedback.

**Comment by iChenLei** [comment]
v2.1.0 released, so close this issue
