### ISSUE TITLE
Mobx 6 got `Exception: TypeError: Cannot read properties of undefined` on COLLECTION

### ISSUE THREAD

**Issue by huybuidac** [mobxjs/mobx-vue#83]
If using observable for COLLECTION, we got error while access any property of object.

```ts
export class VM {
  @observable histories: any[] = []

  constructor() {
    makeObservable(this)
    this.loadData()
  }

  @action.bound loadData() {
    this.histories = [
      { id: 1, name: 'test1' },
      { id: 2, name: 'test2' },
    ]
    console.log(this.histories)
  }
}
```

![image](https://user-images.githubusercontent.com/7322305/144210276-7af64e88-6db3-4103-be8d-9afa0c278db4.png)

**Comment by iChenLei** [comment]
Maybe you should report this issue to mobxjs/mobx repository? @huybuidac

**Comment by huybuidac** [comment]
@iChenLei I don't see any unit test for collection on mobx-vue `2.1.0`, you can make a simple unittest for it :(

I'm using with vuetify v-data-table, and got this error.

**Comment by iChenLei** [comment]
please provide minimal reprodcue code repo([codesandbox](https://codesandbox.io) or [stackblitz](https://stackblitz.io)) or snippet, thanks.
